name: Capsula
description: Amr Abed's Blog
url: "https://amrabed.me"
baseurl: "/blog"

disqus: amrabed
google_analytics: UA-87254560-1

permalink: /:title

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins:
- jekyll-feed
#- jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
  - CNAME
  - docker-compose.yml
  - sonar-project.properties