version: "3"
services:
  blog:
    image: jekyll/jekyll:latest
    container_name: jekyll
    command: jekyll build --watch
    restart: always
    volumes:
      - $BLOG_DIR:/srv/jekyll/_site
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
